name: Home Backup

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  container-image:
    uses: ionutbalutoiu/gha-utils/.github/workflows/docker-buildx.yaml@main
    with:
      image_name: home-backup
      context: .
      platforms: linux/amd64, linux/arm64
    secrets: inherit
